package com.emeraldblast.p6.message.api.connection.kernel_context.context_object

import com.emeraldblast.p6.message.di.SessionId
import com.emeraldblast.p6.message.di.SystemUsername
import dagger.assisted.Assisted
import dagger.assisted.AssistedInject
import java.util.*

/**
 * Provide username, encryption key, and session id. These are for making message
 */
data class SessionImp @AssistedInject constructor(
    @SessionId
    private val sessionId: String,
    @SystemUsername
    private val systemUsername: String,
    @Assisted private val key: String
) : Session {
    companion object {
        /**
         * [sessionId] autogenerated
         * [systemUsername] fetched from system
         */
        fun autoCreate(key: String): SessionImp {
            return SessionImp(
                sessionId = UUID.randomUUID().toString(),
                systemUsername = System.getProperty("user.name"),
                key = key
            )
        }
    }

    override fun getSystemUserName(): String {
        return this.systemUsername
    }

    override fun getKey(): String {
        return this.key
    }

    override fun getSessionId(): String {
        return this.sessionId
    }
}
